<?php
/**
 *    @version 1.0
 *    @package hwdVideoShare
 *    @copyright Juan José Ramírez Escribano
 *    @license http://www.gnu.org/copyleft/gpl.html GNU/GPL
 ***
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU General Public License as published by
 *    the Free Software Foundation, either version 3 of the License, or
 *    (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU General Public License for more details.
 *
 *    You should have received a copy of the GNU General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 ***
 *    New Language Definitions are located at bottom of file
 *    DEFINITIONS HAVE FORM
 *    ---------------------
 *    DEFINE("_HWDVIDS_NAV_VIDEOS","Videos"); // Videos
 *           \___________________/  \_____/      \____/
 *            |                 |    |    \_____  \   \_____________________
 *            | PHP LANGUAGE    |    | LANGUAGE \__ \    COPY OF ORIGINAL   |
 *            | DEFINTIONS      |    | TRANSLATION |  \  ENGLISH DEFINITION |
 *            |_________________|    |_____________|    \___________________|
 ***
 *    TRANSLATOR CREDITS CAN GO HERE::
 *    ORIGINAL ENGLISH FILE BY HIGHWOOD DESIGN
 **/
defined( '_JEXEC' ) or die( 'No está permitido acceder directamente aquí.' );

DEFINE("_ADMIN_HWDVIDS_SETT_TABLAYOUT","Disposición");
DEFINE("_ADMIN_HWDVIDS_SETT_VIDEOS","Listas de vídeo");
DEFINE("_ADMIN_HWDVIDS_SETT_VPP","Vídeos por página");
DEFINE("_ADMIN_HWDVIDS_SETT_VPP_DESC","Establece el número de vídeos mostrados por página");
DEFINE("_ADMIN_HWDVIDS_SETT_FVIDS","Vídeos destacados");
DEFINE("_ADMIN_HWDVIDS_SETT_FVIDS_DESC","Establece el número de vídeos destacados mostrados en la página principal");
DEFINE("_ADMIN_HWDVIDS_SETT_GROUPS","Listas de grupos");
DEFINE("_ADMIN_HWDVIDS_SETT_GPP","Grupos por página");
DEFINE("_ADMIN_HWDVIDS_SETT_GPP_DESC","Establece el número de grupos mostrados por página");
DEFINE("_ADMIN_HWDVIDS_SETT_FGROUPS","Grupos destacados");
DEFINE("_ADMIN_HWDVIDS_SETT_FGROUPS_DESC","Establece el número de grupos destacados mostrados en la página de grupos");
DEFINE("_ADMIN_HWDVIDS_SETT_COMMENTS","Listas de comentarios");
DEFINE("_ADMIN_HWDVIDS_SETT_CPP","Comentarios por página");
DEFINE("_ADMIN_HWDVIDS_SETT_CPP_DESC","Establece el número de comentarios mostrados por página");
DEFINE("_ADMIN_HWDVIDS_SETT_PLUGINS","Gestión de extensiones");
DEFINE("_ADMIN_HWDVIDS_SETT_TEMPLATE","Seleccionar plantilla");
DEFINE("_ADMIN_HWDVIDS_SETT_TEMPLATE_DESC","Elige la extensión de plantilla de hwdVideoShare. Para añadir más plantillas, instala la extensión de plantilla a través del gestor de extensiones.");
DEFINE("_ADMIN_HWDVIDS_SETT_LANGUAGE","Selección de idioma");
DEFINE("_ADMIN_HWDVIDS_SETT_ROUNDEDC","Esquinas redondeadas");
DEFINE("_ADMIN_HWDVIDS_SETT_RADIUSRC","Radio de esquinas redondeadas");
DEFINE("_ADMIN_HWDVIDS_SETT_RADIUSRC_DESC","Elige el radio de las esquinas redondeadas (en pixels)");
DEFINE("_ADMIN_HWDVIDS_SETT_LOGS","Registros de conversión de vídeos");
DEFINE("_ADMIN_HWDVIDS_SETT_LOGCONVERT","¿Se registran las conversiones de vídeo?");
DEFINE("_ADMIN_HWDVIDS_SETT_DEBUG","Depuración de conversiones de vídeo");
DEFINE("_ADMIN_HWDVIDS_SETT_DEBUGCONVERT","¿Se deben depurar las conversiones de vídeo?");
DEFINE("_ADMIN_HWDVIDS_SETT_DEBUG_DESC","Volcar la salida de la conversión a la pantalla durante la conversión de vídeo para depurar");
DEFINE("_ADMIN_HWDVIDS_SETT_ORIGINALS","Vídeo original");
DEFINE("_ADMIN_HWDVIDS_SETT_DELETEO","¿Borrar los vídeos originales?");
DEFINE("_ADMIN_HWDVIDS_SETT_DELETEO_DESC","Borra los vídeos originales tras una conversión con éxito (muy recomendado)");
DEFINE("_ADMIN_HWDVIDS_SETT_NOTIFICATIONS","Notificaciones de administrador");
DEFINE("_ADMIN_HWDVIDS_SETT_NOTIFYVID","¿Notificar tras una nueva subida de vídeo?");
DEFINE("_ADMIN_HWDVIDS_SETT_NOTIFYVID_DESC","Envía una notificación de correo cuando un usuario sube un vídeo");
DEFINE("_ADMIN_HWDVIDS_SETT_NOTIFYG","¿Notificar tras la creación de un nuevo grupo?");
DEFINE("_ADMIN_HWDVIDS_SETT_NOTIFYG_DESC","Envía una notificación de correo cuando un usuario crea un nuevo grupo");
DEFINE("_ADMIN_HWDVIDS_SETT_NOTIFYC","¿Notificar tras crear un nuevo comentario?");
DEFINE("_ADMIN_HWDVIDS_SETT_NOTIFYC_DESC","Envía una notificación de correo cuando un usuario escribe un nuevo comentario");
DEFINE("_ADMIN_HWDVIDS_SETT_SENTTO","Enviar notificaciones a:");
DEFINE("_ADMIN_HWDVIDS_SETT_SENDTO_DESC","La dirección de correo que debe recibir las notificiaciones de correo");
DEFINE("_ADMIN_HWDVIDS_SETT_INTEGRATIONS","Integraciones");
DEFINE("_ADMIN_HWDVIDS_SETT_ACCESS","Acceso");
DEFINE("_ADMIN_HWDVIDS_SETT_GUESTCOMMS","¿Permitir comentarios de invitado?");
DEFINE("_ADMIN_HWDVIDS_SETT_GUESTCOMMS_DESC","Permite a los usuarios que no han accedido añadir comentarios a vídeos/grupos");
DEFINE("_ADMIN_HWDVIDS_SETT_01","1");
DEFINE("_ADMIN_HWDVIDS_SETT_02","2");
DEFINE("_ADMIN_HWDVIDS_SETT_03","3");
DEFINE("_ADMIN_HWDVIDS_SETT_04","4");
DEFINE("_ADMIN_HWDVIDS_SETT_05","5");
DEFINE("_ADMIN_HWDVIDS_SETT_06","6");
DEFINE("_ADMIN_HWDVIDS_SETT_07","7");
DEFINE("_ADMIN_HWDVIDS_SETT_08","8");
DEFINE("_ADMIN_HWDVIDS_SETT_09","9");
DEFINE("_ADMIN_HWDVIDS_SETT_10","10");
DEFINE("_ADMIN_HWDVIDS_SETT_15","15");
DEFINE("_ADMIN_HWDVIDS_SETT_20","20");
DEFINE("_ADMIN_HWDVIDS_SETT_25","25");
DEFINE("_ADMIN_HWDVIDS_SETT_30","30");
DEFINE("_ADMIN_HWDVIDS_SETT_35","35");
DEFINE("_ADMIN_HWDVIDS_SETT_40","40");
DEFINE("_ADMIN_HWDVIDS_SETT_45","45");
DEFINE("_ADMIN_HWDVIDS_SETT_50","50");
DEFINE("_ADMIN_HWDVIDS_SETT_APPROVALS","Auto aprobaciones");
DEFINE("_ADMIN_HWDVIDS_SETT_AA3VIDS","¿Auto-aprobar vídeos de terceros?");
DEFINE("_ADMIN_HWDVIDS_SETT_AAGROUPS","¿Auto-aprobar grupos?");
DEFINE("_ADMIN_HWDVIDS_SETT_AACOMMS","¿Auto-aprobar comentarios?");
DEFINE("_ADMIN_HWDVIDS_SETT_AAVIDS_DESC","¿Deben ser aprobados los vídeos tras la conversión?");
DEFINE("_ADMIN_HWDVIDS_SETT_AA3VIDS_DESC","¿Deben ser automáticamente aprobados los vídeos de terceros (de YouTube etc)?");
DEFINE("_ADMIN_HWDVIDS_SETT_AAGROUPS_DESC","¿Deben ser automáticamente aprobados los grupos tras su creación por los usuarios?");
DEFINE("_ADMIN_HWDVIDS_SETT_LOCALUPLD","Subidas de ficheros locales");
DEFINE("_ADMIN_HWDVIDS_SETT_DISABLELCOAL","Desactivar subidas de ficheros locales");
DEFINE("_ADMIN_HWDVIDS_SETT_DISABLELCOAL_DESC","Desactivar esta característica evita que las personas puedan subir vídeos de sus ordenadores locales. Sólo podrán añadir vídeos de terceros como YouTube. Si desactivas esto recuerda activarlo al menos para una página de terceros.");
DEFINE("_ADMIN_HWDVIDS_SETT_THIRDPARTYVSITES","Páginas de vídeo de terceros");
DEFINE("_ADMIN_HWDVIDS_SETT_ALLOWYOUTUBE","Permitir vídeos de YouTube");
DEFINE("_ADMIN_HWDVIDS_SETT_ALLOWYOUTUBE_DESC","Permite que los usuarios añadan vídeos de YouTube");
DEFINE("_ADMIN_HWDVIDS_SETT_GOOGLE","Permitir vídeos de Google Videos");
DEFINE("_ADMIN_HWDVIDS_SETT_GOOGLE_DESC","Permite a los usuarios añadir vídeos de Google");
DEFINE("_ADMIN_HWDVIDS_SETT_EYESPOT","Permitir vídeos de Eyespot");
DEFINE("_ADMIN_HWDVIDS_SETT_EYESPOT_DESC","Permite a los usuarios añadir vídeos de Eyespot");
DEFINE("_ADMIN_HWDVIDS_SETT_JUMPCUT","Permitir vídeos de Jumpcut");
DEFINE("_ADMIN_HWDVIDS_SETT_JUMPCUT_DESC","Permite a los usuarios añadir vídeos de Jumpcut");
DEFINE("_ADMIN_HWDVIDS_SETT_REVVER","Permitir vídeos de Revver");
DEFINE("_ADMIN_HWDVIDS_SETT_REVVER_DESC","Permite a los usuarios añadir vídeos de Revver");
DEFINE("_ADMIN_HWDVIDS_SETT_VIMEO","Permitir vídeos de Vimeo");
DEFINE("_ADMIN_HWDVIDS_SETT_VIMEO_DESC","Permite a los usuarios añadir vídeos de Vimeo");
DEFINE("_ADMIN_HWDVIDS_SETT_BLIPTV","Permitir vídeos de Blip.tv");
DEFINE("_ADMIN_HWDVIDS_SETT_BLIPTV_DESC","Permite a los usuarios añadir vídeos de Blip.tv");
DEFINE("_ADMIN_HWDVIDS_SETT_STAGE6","Permitir vídeos de Stage6 [DivX]");
DEFINE("_ADMIN_HWDVIDS_SETT_STAGE6_DESC","Permite a los usuarios añadir vídeos de  Stage6 [Esto requiere que el usuario tenga que usar el reproductor web de DivX]");
DEFINE("_ADMIN_HWDVIDS_SETT_FLVPLAYER","Ajustes del reproductor de vídeo");
DEFINE("_ADMIN_HWDVIDS_SETT_FLVPLAY_WIDTH","Ancho del reproductor de vídeo (px)");
DEFINE("_ADMIN_HWDVIDS_SETT_FLVPLAY_WIDTH_DESC","Obliga al reproductor de vídeo a tener un ancho concreto (p.ej. 450px). Ten en cuenta que esto se utilizará para todos los anchos de vídeos de terceros.");
DEFINE("_ADMIN_HWDVIDS_SETT_FLVPLAY_HEIGHT","Alto del reproductor de vídeo (px)");
DEFINE("_ADMIN_HWDVIDS_SETT_FLVPLAY_HEIGHT_DESC","Obliga al reproductor de vídeo a tener un alto concreto (p.ej. 450px). Ten en cuenta que esto se utilizará para todos los altos de vídeos de terceros.");
DEFINE("_ADMIN_HWDVIDS_SETT_FLVPLAY_AUTOPLAY","Reproducción automática");
DEFINE("_ADMIN_HWDVIDS_SETT_FLVPLAY_AUTOPLAY_DESC","Reproduce automáticamente el vídeo cuando carga la página");
DEFINE("_ADMIN_HWDVIDS_SETT_FLVPLAY_AUTOLOAD","Carga automática");
DEFINE("_ADMIN_HWDVIDS_SETT_FLVPLAY_AUTOLOAD_DESC","Carga automáticamente el vídeo cuando carga la página");
DEFINE("_ADMIN_HWDVIDS_SETT_FLVPLAY_BUFFER","Tiempo de buffer (segundos)");
DEFINE("_ADMIN_HWDVIDS_SETT_FLVPLAY_BUFFER_DESC","Número de segundos para almacenar en buffer. Por defecto establecido en 5.");
DEFINE("_ADMIN_HWDVIDS_SETT_FLVPLAY_SHOWSTOP","Mostrar el botón parar");
DEFINE("_ADMIN_HWDVIDS_SETT_FLVPLAY_SHOWSTOP_DESC","Muestra el botón parar en el reproductor de vídeo");
DEFINE("_ADMIN_HWDVIDS_SETT_FLVPLAY_SHOWVOL","Mostrar el deslizador de volumen");
DEFINE("_ADMIN_HWDVIDS_SETT_FLVPLAY_SHOWVOL_DESC","Muestra el deslizador de volumen en el reproductor de vídeo");
DEFINE("_ADMIN_HWDVIDS_SETT_FLVPLAY_SHOWTIME","Mostrar tiempo");
DEFINE("_ADMIN_HWDVIDS_SETT_FLVPLAY_SHOWTIME_DESC","Muestra el tiempo de reproducción de la posición actual");
DEFINE("_ADMIN_HWDVIDS_SETT_FLVPLAY_LOOP","Reiniciar película");
DEFINE("_ADMIN_HWDVIDS_SETT_FLVPLAY_LOOP_DESC","Reproduce de nuevo la película al terminar");
DEFINE("_ADMIN_HWDVIDS_SETT_FLVPLAY_IMAGE","Imagen de logotipo y posición");
DEFINE("_ADMIN_HWDVIDS_SETT_FLVPLAY_IMAGE_DESC","Carga una imagen sobre el vídeo y la sitúa en las coordenadas x e y (por ejemplo url|x|y)");
DEFINE("_ADMIN_HWDVIDS_SETT_FLVPLAY_COLOR","Color del reproductor");
DEFINE("_ADMIN_HWDVIDS_SETT_FLVPLAY_COLOR_DESC","Color de fondo de la barra del reproductor en formato hexadecimal sin empezar por # (p. ej. 333333)");
DEFINE("_ADMIN_HWDVIDS_SETT_FLVPLAY_LDCOLOR","Color de carga");
DEFINE("_ADMIN_HWDVIDS_SETT_FLVPLAY_LDCOLOR_DESC","El color de la barra de carga en formato hexadecimal sin empezar por # (p. ej. 333333)");
DEFINE("_ADMIN_HWDVIDS_SETT_FLVPLAY_BGCOLOR0","Color de fondo");
DEFINE("_ADMIN_HWDVIDS_SETT_FLVPLAY_BGCOLOR0_DESC","El color de fondo en formato hexadecimal sin empezar por # (p. ej. 333333)");
DEFINE("_ADMIN_HWDVIDS_SETT_FLVPLAY_BGCOLOR1","Degradado de color 1");
DEFINE("_ADMIN_HWDVIDS_SETT_FLVPLAY_BGCOLOR1_DESC","El primer color del degradado del fondo en formato hexadecimal sin empezar por # (p. ej. 333333)");
DEFINE("_ADMIN_HWDVIDS_SETT_FLVPLAY_BGCOLOR2","Degradado de color 2");
DEFINE("_ADMIN_HWDVIDS_SETT_FLVPLAY_BGCOLOR2_DESC","El segundo color del degradado del fondo en formato hexadecimal sin empezar por # (p. ej. 333333)");
DEFINE("_ADMIN_HWDVIDS_SETT_FLVPLAY_BUTCOLOR","Color del botón");
DEFINE("_ADMIN_HWDVIDS_SETT_FLVPLAY_BUTCOLOR_DESC","El color de los botones en formato hexadecimal sin empezar por # (p. ej. 333333)");
DEFINE("_ADMIN_HWDVIDS_SETT_FLVPLAY_BUTHCOLOR","Color de botones al pasar por encima");
DEFINE("_ADMIN_HWDVIDS_SETT_FLVPLAY_BUTHCOLOR_DESC","Color de los botones al pasar por encima el ratón en formato hexadecimal sin empezar por # (p. ej. 333333)");
DEFINE("_ADMIN_HWDVIDS_SETT_FLVPLAY_SLCOLOR0","Color de deslizador 1");
DEFINE("_ADMIN_HWDVIDS_SETT_FLVPLAY_SLCOLOR0_DESC","El primer color del degradado del deslizador enformato hexadecimal sin empezar por # (p. ej. 333333)");
DEFINE("_ADMIN_HWDVIDS_SETT_FLVPLAY_SLCOLOR1","Color del deslizador 2");
DEFINE("_ADMIN_HWDVIDS_SETT_FLVPLAY_SLCOLOR1_DESC","El segundo color del degradado del deslizador en formato hexadecimal sin empezar por # (p. ej. 333333)");
DEFINE("_ADMIN_HWDVIDS_SETT_FLVPLAY_SLCOLORH","Color del deslizador al pasar por encima");
DEFINE("_ADMIN_HWDVIDS_SETT_FLVPLAY_SLCOLORH_DESC","El color de la barra al pasar por encima el ratón en formato hexadecimal sin empezar por # (p. ej. 333333)");
DEFINE("_ADMIN_HWDVIDS_SETT_FLVPLAY_BUFFMESS","Mensaje de buffer");
DEFINE("_ADMIN_HWDVIDS_SETT_FLVPLAY_BUFFMESS_DESC","El mensaje de buffer. Por defecto es Buffering _n_, _n_ mostrado como porcentaje.");
DEFINE("_ADMIN_HWDVIDS_SETT_FLVPLAY_BUFFCOL","Color de buffer");
DEFINE("_ADMIN_HWDVIDS_SETT_FLVPLAY_BUFFCOL_DESC","El color del mensaje de buffering");
DEFINE("_ADMIN_HWDVIDS_SETT_FLVPLAY_BUFFBGCOL","Color de fondo de buffer");
DEFINE("_ADMIN_HWDVIDS_SETT_FLVPLAY_BUFFBGCOL_DESC","El color de fondo del mensaje de buffering");
DEFINE("_ADMIN_HWDVIDS_SETT_FLVPLAY_SHOWBUFFBG","Mostrar el color de fondo del Buffer");
DEFINE("_ADMIN_HWDVIDS_SETT_FLVPLAY_SHOWBUFFBG_DESC","0 para ocultar el color de fondo del mensaje de buffering");
DEFINE("_ADMIN_HWDVIDS_SETT_FLVPLAY_SHOWBAR","Mostrar barra de reproducción");
DEFINE("_ADMIN_HWDVIDS_SETT_FLVPLAY_SHOWBAR_DESC","Modo de visualización de la barra del reproductor: autoesconder, siempre o nunca.");
DEFINE("_ADMIN_HWDVIDS_SETT_FLVPLAY_SHOWLDBAR","Mostrar barra de carga");
DEFINE("_ADMIN_HWDVIDS_SETT_FLVPLAY_SHOWLDBAR_DESC","Modo de visualización de la barra de carga: autoesconder, siempre o nunca.");
DEFINE("_ADMIN_HWDVIDS_SETT_FLVPLAY_SHOWFS","Mostrar pantalla completa");
DEFINE("_ADMIN_HWDVIDS_SETT_FLVPLAY_SHOWFS_DESC","1 para mostrar el botón de pantalla completa (necesita el reproductor Flash Player 9.0.16.60 o superior)");
DEFINE("_ADMIN_HWDVIDS_SETT_FLVPLAY_SHOWMOUSE","Mostrar ratón");
DEFINE("_ADMIN_HWDVIDS_SETT_FLVPLAY_SHOWMOUSE_DESC","Muestra el cursor del ratón: autoesconder, siempre o nunca.");
DEFINE("_ADMIN_HWDVIDS_SETT_FLVPLAY_OCDEST","OnClick");
DEFINE("_ADMIN_HWDVIDS_SETT_FLVPLAY_OCDEST_DESC","La URL destino cuando se pulse en el vídeo. Por defecto playpause significa que el vídeo se reproduce/pausa al pulsar. Para eliminar eventos, establecer en ninguno.");
DEFINE("_ADMIN_HWDVIDS_SETT_FLVPLAY_OCTARGET","OnClick Target");
DEFINE("_ADMIN_HWDVIDS_SETT_FLVPLAY_OCTARGET_DESC","Establece el target de la URL cuando se pulse el vídeo. Por defecto _self. Para abrir una nueva ventana establecer en _blank.");
DEFINE("_ADMIN_HWDVIDS_SETT_FLVPLAY_ODCDEST","OnDoubleClick");
DEFINE("_ADMIN_HWDVIDS_SETT_FLVPLAY_ODCDEST_DESC","Acción que se desencadenará en double click: ninguno, pantalla completa, playpause o la URL a abrir.");
DEFINE("_ADMIN_HWDVIDS_SETT_FLVPLAY_ODCTARGET","OnDoubleClick Target");
DEFINE("_ADMIN_HWDVIDS_SETT_FLVPLAY_ODCTARGET_DESC","El target de la URL cuando se haga doble click sobre el vídeo. Por defecto es _self. Para abrir una nueva ventana establecer en _blank.");
DEFINE("_ADMIN_HWDVIDS_SETT_FLVPLAY_TIMEOUT","Player Timeout");
DEFINE("_ADMIN_HWDVIDS_SETT_FLVPLAY_TIMEOUT_DESC","El timeout en milisegundos antes de que el reproductor se esconda (cuando autoesconder esté activado). Por defecto es 1500.");
DEFINE("_ADMIN_HWDVIDS_SETT_FLVPLAY_VIDBG","Fondo de vídeo vacío");
DEFINE("_ADMIN_HWDVIDS_SETT_FLVPLAY_VIDBG_DESC","Color de fondo de flash, cuando no se está mostrando ningún vídeo.");
DEFINE("_ADMIN_HWDVIDS_SETT_FLVPLAY_INIVOL","Volumen inicial");
DEFINE("_ADMIN_HWDVIDS_SETT_FLVPLAY_INIVOL_DESC","El volumen inicial, entre 0 y 200.");
DEFINE("_ADMIN_HWDVIDS_SETT_FLVPLAY_BARALPHA","Transparencia del reproductor");
DEFINE("_ADMIN_HWDVIDS_SETT_FLVPLAY_BARALPHA_DESC","La transparencia de la barra del reproductor, entre 0 y 100.");
DEFINE("_ADMIN_HWDVIDS_SETT_ALWAYS","Siempre");
DEFINE("_ADMIN_HWDVIDS_SETT_AUTOHIDE","Autoesconder");
DEFINE("_ADMIN_HWDVIDS_SETT_NEVER","Nunca");
DEFINE("_ADMIN_HWDVIDS_SETT_TBLANK","_blank");
DEFINE("_ADMIN_HWDVIDS_SETT_TPARENT","_parent");
DEFINE("_ADMIN_HWDVIDS_SETT_TSELF","_self");
DEFINE("_ADMIN_HWDVIDS_SETT_TTOP","_top");
DEFINE("_ADMIN_HWDVIDS_SETT_CAPTCHA","Imagen de seguridad Captcha");
DEFINE("_ADMIN_HWDVIDS_SETT_DISABLECAPTCHA","¿Desactivar Captcha?");
DEFINE("_ADMIN_HWDVIDS_SETT_DISABLECAPTCHA_DESC","Desactiva la imagen captcha de tal forma que no es necesaria una verificación humana.");
DEFINE("_ADMIN_HWDVIDS_SETT_DISABLENAVTABS","Desactivar las pestañas de navegación principal");
DEFINE("_ADMIN_HWDVIDS_SETT_DISABLEVIDTAB","Desactivar la pestaña de vídeo");
DEFINE("_ADMIN_HWDVIDS_SETT_DISABLEVIDTAB_DESC","Desactiva la pestaña de vídeo de tal forma que no aparecerá en la parte superior de la página");
DEFINE("_ADMIN_HWDVIDS_SETT_DISABLECATTAB","Desactivar la pestaña de categoría");
DEFINE("_ADMIN_HWDVIDS_SETT_DISABLECATTAB_DESC","Desactiva la pestaña de categoría de tal forma que no aparecerá en la parte superior de la página");
DEFINE("_ADMIN_HWDVIDS_SETT_DISABLEGRPTAB","Desactivar la pestaña de grupo");
DEFINE("_ADMIN_HWDVIDS_SETT_DISABLEGRPTAB_DESC","Desactiva la pestaña de grupo de tal forma que no aparecerá en la parte superior de la página");
DEFINE("_ADMIN_HWDVIDS_SETT_DISABLEULDTAB","Desactivar la pestaña de subida");
DEFINE("_ADMIN_HWDVIDS_SETT_DISABLEULDTAB_DESC","Desactiva la pestaña de subida de tal forma que no aparecerá en la parte superior de la página");
DEFINE("_ADMIN_HWDVIDS_SETT_SHOWCOPYRIGHT","Enlace de créditos");
DEFINE("_ADMIN_HWDVIDS_SETT_SHOWCREDIT","¿Mostrar powered by?");
DEFINE("_ADMIN_HWDVIDS_SETT_SHOWCREDIT_DESC","Agradecemos los enlaces de retorno, pero si eres un suscriptor puedes desactivar esto");
DEFINE("_ADMIN_HWDVIDS_SETT_VIDEDIT","Características de edición y eliminación de vídeos");
DEFINE("_ADMIN_HWDVIDS_SETT_ALLOWEDIT","¿Permitir edición de vídeo?");
DEFINE("_ADMIN_HWDVIDS_SETT_ALLOWEDIT_DESC","Permite a los usuarios editar sus propios vídeos a través de la interfaz de la página");
DEFINE("_ADMIN_HWDVIDS_SETT_ALLOWDEL","¿Permitir borrar vídeos?");
DEFINE("_ADMIN_HWDVIDS_SETT_ALLOWDEL_DESC","Permite a los usuarios eliminar sus propios vídeos a través de la interfaz de la página");
DEFINE("_ADMIN_HWDVIDS_SETT_RECONFLV","Reconvertir vídeos FLV/MP4?");
DEFINE("_ADMIN_HWDVIDS_SETT_RECONFLV_DESC","¿Quieres reconvertir vídeos flv utilizando tus ajustes de conversión o simplemente copiarlos directamente en hwdVideoShare?");
DEFINE("_ADMIN_HWDVIDS_SETT_FLVPLAYERSEL","Selecciona tu reproductor de vídeo");
DEFINE("_ADMIN_HWDVIDS_SETT_FLVPLAYERSEL_DESC","Selecciona un reproductor de vídeo de la lista de abajo para utilizarlo en tu página web. Este es el reproductor que será utilizado para reproducir los vídeos que los usuarios han subido a tu página web desde sus ordenadores locales.");
DEFINE("_ADMIN_HWDVIDS_SETT_UPLDMETH","Método de subida");
DEFINE("_ADMIN_HWDVIDS_SETT_UPLDMETH_DESC","Selecciona el método de subida que quieres que se utilice para procesar las subidas de ficheros. El método avanzado (PERL) requiere configuración manual de scripts de Perl.");
DEFINE("_ADMIN_HWDVIDS_SETT_UPLDMETH_ADVPERL","El <a href=\"http://documentation.hwdmediashare.co.uk/wiki/Advanced_Perl_Upload_Method\" target=\"_blank\"><b>método avanzado (PERL)</b></a> utiliza <a href=\"http://uber-uploader.sourceforge.net/\" target=\"_blank\">Uber Uploader</a> para procesar las subidas a través de scripts de Perl. Este método permite ver una barra de progreso en tiempo real y una subida de ficheros con límites superiores. Puedes configurar manualmente los scripts de Perl para funcionar adecuadamente en tu servidor.");
DEFINE("_ADMIN_HWDVIDS_SETT_UPLDMETH_ADVFLASH","El <a href=\"http://documentation.hwdmediashare.co.uk/wiki/Advanced_Flash_Upload_Method\" target=\"_blank\"><b>método avanzado (FLASH)</b></a> utiliza <a href=\"http://www.pixeline.be/experiments/jqUploader/\" target=\"_blank\">jqUploader</a> para procesar las subidas utilizando un widget de subida de ficheros basado en flash, permitiendo mostrar una barra de progreso y un porcentaje.");
DEFINE("_ADMIN_HWDVIDS_SETT_ADVPERL","Avanzado (PERL)");
DEFINE("_ADMIN_HWDVIDS_SETT_ADVFLASH","Avanzado (FLASH)");
DEFINE("_ADMIN_HWDVIDS_SETT_ADVAJAX","Avanzado (AJAX)");
DEFINE("_ADMIN_HWDVIDS_SETT_BASPHP","Básico (PHP)");
DEFINE("_ADMIN_HWDVIDS_SETT_INTEGRATIONSGJ","Integración con grupos Jive");
DEFINE("_ADMIN_HWDVIDS_SETT_VISITSITE","[Visitar página web]");
DEFINE("_ADMIN_HWDVIDS_SETT_ALLOWFT","Tipos de ficheros permitidos");
DEFINE("_ADMIN_HWDVIDS_SETT_ALLOWFT_CHECK","Por favor, seleccione los formatos de ficheros que se permiten.");
DEFINE("_ADMIN_HWDVIDS_SETT_ALLOWFT_NOCHECK","No tienes los programas de terceros necesarios para convertir los ficheros de vídeo. <b>Sólo puedes aceptar el formato de vídeo flv</b>. Si tienes los programas necesarios instalados, activa este ajuste en la pestaña de configuración.");
DEFINE("_ADMIN_HWDVIDS_SETT_MAXFS","Tamaño máximo de subida");
DEFINE("_ADMIN_HWDVIDS_SETT_MAXUPLD","Tamaño máximo de subida (MB)");
DEFINE("_ADMIN_HWDVIDS_SETT_MAXUPLD_DESC","Introduce el tamaño máximo de fichero que quieras aceptar. Véase más abajo acerca de algunas restricciones.");
DEFINE("_ADMIN_HWDVIDS_SETT_MAXUPLD_FLASH","Debido a limitaciones en el reproductor de flash, el tamaño máximo permitido para el método Flash es de 100 MB");
DEFINE("_ADMIN_HWDVIDS_SETT_MAXUPLD_FLASHLIM","Tamaño máximo para el reproductor de flash = 100 MB");
DEFINE("_ADMIN_HWDVIDS_SETT_RESTRICTFLASH","Limitaciones de Flash");
DEFINE("_ADMIN_HWDVIDS_SETT_PLAYERALIGN","Alineamiento del reproductor de vídeo");
DEFINE("_ADMIN_HWDVIDS_SETT_FLVALIGN","Alineamiento del reproductor");
DEFINE("_ADMIN_HWDVIDS_SETT_FLVALIGN_DESC","¿Quieres alinear el reproductor a la izquierda, derecha o en el centro?");
DEFINE("_ADMIN_HWDVIDS_SETT_LEFT","Izquierda");
DEFINE("_ADMIN_HWDVIDS_SETT_RIGHT","Derecha");
DEFINE("_ADMIN_HWDVIDS_SETT_CENTER","Centro");
DEFINE("_ADMIN_HWDVIDS_SETT_INFOALIGN","¿Alinear información del vídeo junto al vídeo?");
DEFINE("_ADMIN_HWDVIDS_SETT_INFOALIGN_DESC","Si eliges alinear el reproductor del vídeo a la izquierda o a la derecha puedes elegir poner la información del vídeo junto a el. Esto maximiza el espacio disponible en tu página. Si quieres alinear el vídeo en el centro necesitarás poner la información debajo.");
DEFINE("_ADMIN_HWDVIDS_SETT_SWITCHOFF","Desactivar");
DEFINE("_ADMIN_HWDVIDS_SETT_DEFAULTSO","Opciones de compartición por defecto");
DEFINE("_ADMIN_HWDVIDS_SETT_DSACCESS","Opciones de acceso por defecto");
DEFINE("_ADMIN_HWDVIDS_SETT_DSACCESS_DESC","Establece los ajustes de acceso por defecto para nuevos vídeos");
DEFINE("_ADMIN_HWDVIDS_SETT_USACCESS","¿Puede cambiarlo el usuario?");
DEFINE("_ADMIN_HWDVIDS_SETT_USACCESS_DESC","¿Puede el usuario cambiar este valor por defecto? Si no, entonces la opción no se mostrará durante las subidas");
DEFINE("_ADMIN_HWDVIDS_SETT_DSCOMMS","Ajustes de comentarios por defecto");
DEFINE("_ADMIN_HWDVIDS_SETT_DSCOMMS_DESC","Establece los ajustes por defecto de comentarios para nuevos vídeos");
DEFINE("_ADMIN_HWDVIDS_SETT_USCOMMS","¿Puede cambiarlo el usuario?");
DEFINE("_ADMIN_HWDVIDS_SETT_USCOMMS_DESC","¿Puede el usuario cambiar este valor por defecto? Si no, entonces esta opción no se mostrará durante las subidas");
DEFINE("_ADMIN_HWDVIDS_SETT_DSEMBED","Ajustes de incrustación por defecto");
DEFINE("_ADMIN_HWDVIDS_SETT_DSEMBED_DESC","Establece los ajustes de incrustación por defecto par anuevos vídeos");
DEFINE("_ADMIN_HWDVIDS_SETT_USEMBED","¿Puede cambiarlo el usuario?");
DEFINE("_ADMIN_HWDVIDS_SETT_USEMBED_DESC","¿Puede el usuario cambiar este valor por defecto? Si no, entonces esta opción no se mostrará durante las subidas");
DEFINE("_ADMIN_HWDVIDS_SETT_DSRATE","Ajustes de puntuación por defecto");
DEFINE("_ADMIN_HWDVIDS_SETT_DSRATE_DESC","Establece los ajustes de puntuación por defecto para nuevos vídeos");
DEFINE("_ADMIN_HWDVIDS_SETT_USRATE","¿Puede cambiarlo el usuario?");
DEFINE("_ADMIN_HWDVIDS_SETT_USRATE_DESC","¿Puede el usuario cambiar este valor por defecto? Si no, entonces esta opción no se mostrará durante las subidas");
DEFINE("_ADMIN_HWDVIDS_SETT_MAINACCESS","Detalles de acceso de grupo principales");
DEFINE("_ADMIN_HWDVIDS_SETT_MAINCOMACCESS","Acceso de componente principal");
DEFINE("_ADMIN_HWDVIDS_SETT_MAINCOMACCESS_DESC","Establece los grupos que pueden acceder al componente hwdVideoShare");
DEFINE("_ADMIN_HWDVIDS_SETT_INCLUDECHILD_DESC","¿Quieres incluir todos los grupos-hijo de la selección de arriba?");
DEFINE("_ADMIN_HWDVIDS_SETT_GROUPACCESS","Función de acceso a grupos");
DEFINE("_ADMIN_HWDVIDS_SETT_GROUPACCESS_DESC","Establece los grupos de Joomla que pueden acceder a las funciones de grupo de hwdVideoShare");
DEFINE("_ADMIN_HWDVIDS_SETT_CBAVAWIDTH","Ancho de imagen de avatar");
DEFINE("_ADMIN_HWDVIDS_SETT_VIDTHUMB","Miniaturas de vídeo");
DEFINE("_ADMIN_HWDVIDS_SETT_THUMBW","Ancho de las miniaturas");
DEFINE("_ADMIN_HWDVIDS_SETT_HEAD1","Ruta a herramientas de terceros");
DEFINE("_ADMIN_HWDVIDS_SETT_CNVNSET","Ajustes de conversión para definición stándar");
DEFINE("_ADMIN_HWDVIDS_SETT_CNVNSET_WARNING","ADVERTENCIA: Incrementar la calidad del vídeo de salida puede crear una carga significativa en tu servidor durante el proceso de conversión. También incremente el tamaño del vídeo resultante.");
DEFINE("_ADMIN_HWDVIDS_SETT_CNVTPROG","Conversor preferido");
DEFINE("_ADMIN_HWDVIDS_SETT_CNVTPROG_DESC","Selecciona la utilidad de conversión preferida.");
DEFINE("_ADMIN_HWDVIDS_SETT_CUSTOMENCODEOPT","Opciones de codificación personalizados");
DEFINE("_ADMIN_HWDVIDS_SETT_CUSTOMENCODEOPT_DESC","Añade tus opciones de codificación personalizadas. Estos valores se añadirán directamente al final del comando de codificación. (<b>SÓLO USUARIOS AVANZADOS</b>)");
DEFINE("_ADMIN_HWDVIDS_SETT_WMVFIX","Aplicar arreglo de A/V Sync");
DEFINE("_ADMIN_HWDVIDS_SETT_WMVFIX_DESC","Si tu audio/vídeo no está sincronizado aplica esto. Los ficheros de salida serán más grandes.");
DEFINE("_ADMIN_HWDVIDS_SETT_THUMBFAIL","¿Parar la conversión si una miniatura falla?");
DEFINE("_ADMIN_HWDVIDS_SETT_THUMBFAIL_DESC","¿Quieres parar una conversión de vídeo si la creación de las miniaturas fallan de forma que puedas reintentarlo después?");
DEFINE("_ADMIN_HWDVIDS_SETT_DISABLESEARCHBAR","Desactivar la barra de búsqueda");
DEFINE("_ADMIN_HWDVIDS_SETT_DISABLESEARCHBAR_DESC","Desactiva la barra de búsqueda");
DEFINE("_ADMIN_HWDVIDS_SETT_DISABLEUSERBAR","Desactivar la barra de usuario");
DEFINE("_ADMIN_HWDVIDS_SETT_DISABLEUSERBAR_DESC","Desactiva la barra de usuario que se muestra enlaces a los vídeos del usuario, vídeos favoritos y grupos (sólo se mostrarán cuando un usuario haya iniciado sesión)");
DEFINE("_ADMIN_HWDVIDS_SETT_TRUNCATE","Título &amp; truncado de descripción");
DEFINE("_ADMIN_HWDVIDS_SETT_TRUNTITLE","Truncar títulos");
DEFINE("_ADMIN_HWDVIDS_SETT_TRUNTITLE_DESC","Puedes elegir truncar los títulos de los vídeos y grupos de las páginas de listado principal a este número de caracteres");
DEFINE("_ADMIN_HWDVIDS_SETT_TRUNVDESC","Truncar las descripciones de vídeoTruncate video descriptions");
DEFINE("_ADMIN_HWDVIDS_SETT_TRUNVDESC_DESC","Puedes elegir truncar las descripciones de los vídeos y grupos de las páginas de listado principal a este número de caracteres");
DEFINE("_ADMIN_HWDVIDS_SETT_TRUNCDESC","Truncar las descripciones de las categorías");
DEFINE("_ADMIN_HWDVIDS_SETT_TRUNCDESC_DESC","Puedes elegir truncar las descripciones de las categorías de los vídeos y grupos de las páginas de listado principal a este número de caracteres");
DEFINE("_ADMIN_HWDVIDS_SETT_TRUNGDESC","Truncar descripciones de grupo");
DEFINE("_ADMIN_HWDVIDS_SETT_TRUNGDESC_DESC","Puedes elegir truncar las descripciones de los grupos de los vídeos y grupos de las páginas de listado principal a este número de caracteres");
DEFINE("_ADMIN_HWDVIDS_SETT_SOCBM","Enlaces de Bookmark Social");
DEFINE("_ADMIN_HWDVIDS_SETT_SHOWRATE","¿Mostrar puntuación?");
DEFINE("_ADMIN_HWDVIDS_SETT_SHOWRATE_DESC","¿Mostrar puntuaciones de vídeo en las páginas de listado de vídeos?");
DEFINE("_ADMIN_HWDVIDS_SETT_SHOWVIEWS","¿Mostrar visualizaciones?");
DEFINE("_ADMIN_HWDVIDS_SETT_SHOWVIEWS_DESC","¿Mostrar el número de visualizaciones en las páginas de listado de vídeos?");
DEFINE("_ADMIN_HWDVIDS_SETT_SHOWDURATION","¿Mostrar duración?");
DEFINE("_ADMIN_HWDVIDS_SETT_SHOWDURATION_DESC","¿Mostrar duración en las páginas de listado de vídeo?");
DEFINE("_ADMIN_HWDVIDS_SETT_SHOWUPLDER","¿Mostrar autor?");
DEFINE("_ADMIN_HWDVIDS_SETT_SHOWUPLDER_DESC","¿Mostrar quién subió un vídeo en las páginas de listado de vídeos?");
DEFINE("_ADMIN_HWDVIDS_SETT_AUTOCON","Conversiones automáticas");
DEFINE("_ADMIN_HWDVIDS_SETT_COMMSYS","Integración con el sistema de comentarios");
DEFINE("_ADMIN_HWDVIDS_SETT_COMMCOM","Componente de comentarios");
DEFINE("_ADMIN_HWDVIDS_SETT_COMMCOM_DESC","Qué componente de comentarios de Joomla quieres usar con hwdVideoShare");
DEFINE("_ADMIN_HWDVIDS_SETT_INTGJ","¿Integrar con GroupJive?");
DEFINE("_ADMIN_HWDVIDS_SETT_INTGJ_DESC","La integración está en desarrollo");
DEFINE("_ADMIN_HWDVIDS_SETT_INFORMUPLDRESTRICT","Informar al usuario del tamaño máximo de subida y los tipos de fichero permitidos");
DEFINE("_ADMIN_HWDVIDS_SETT_INFORMUPLDTYPE","Informar al usuario de los criterios de subida");
DEFINE("_ADMIN_HWDVIDS_SETT_INFORMUPLDTYPE_DESC","Esto mostrará el tamaño máximo de fichero y los formatos de vídeo permitidos en la página de subida.");
DEFINE("_ADMIN_HWDVIDS_SETT_AD1","Publicidad junto al reproductor de vídeo");
DEFINE("_ADMIN_HWDVIDS_SETT_SHOWAD1","Mostrar publicidad");
DEFINE("_ADMIN_HWDVIDS_SETT_SHOWAD1_DESC","¿Quieres que se muestre publicidad directamente junto al reproductor de vídeo principal?");
DEFINE("_ADMIN_HWDVIDS_SETT_ADSENSE","Publicidad de AdSense");
DEFINE("_ADMIN_HWDVIDS_SETT_CUSTOM","Publicidad personalizada");
DEFINE("_ADMIN_HWDVIDS_SETT_AD1CUSTOM","Código de publicidad personalizada");
DEFINE("_ADMIN_HWDVIDS_SETT_AD1CUSTOM_DESC","Añade el código para tu publicidad personalizada si no quieres usar AdSense");
DEFINE("_ADMIN_HWDVIDS_SETT_AD1ADCLIENT","ID de editor");
DEFINE("_ADMIN_HWDVIDS_SETT_AD1ADCLIENT_DESC","Por favor, introduce el ID de editor que te haya proporcionado Google AdSense. Es una cadena de texto alfanumérica del estilo pub-123456789876543.");
DEFINE("_ADMIN_HWDVIDS_SETT_AD1ADCHANNEL","Número de canal");
DEFINE("_ADMIN_HWDVIDS_SETT_AD1ADCHANNEL_DESC","Introduce el número de canal que quieres que aparezca en Google AdSense. Es una cadena de texto del estilo 54656789 y NO cualquier cadena de texto que elijas.");
DEFINE("_ADMIN_HWDVIDS_SETT_AD1ADTYPE","Tipo de publicidad");
DEFINE("_ADMIN_HWDVIDS_SETT_AD1ADTYPE_DESC","Elige el tipo de publicidad que quieres que se muestre en tu página. Si estás eligiendo la opción de 'Sólo imagen', por favor usa sólamente uno de estos tamaños: 728X90 - Leaderboard, 468X60 - Banner, 300X250 - Medium Rectangle, 160X600 - Wide Skyscraper and 120X600 - Skyscraper");
DEFINE("_ADMIN_HWDVIDS_SETT_AD1ADUIF","Estilo de esquinas");
DEFINE("_ADMIN_HWDVIDS_SETT_AD1ADUIF_DESC","Opcionalmente, elige uno de los estilos de esquinas prediseñados.");
DEFINE("_ADMIN_HWDVIDS_SETT_ADS_TANDI","Texto e imagen (por defecto)");
DEFINE("_ADMIN_HWDVIDS_SETT_ADS_TEXT","Sólo texto");
DEFINE("_ADMIN_HWDVIDS_SETT_ADS_IMAGE","Sólo imagen");
DEFINE("_ADMIN_HWDVIDS_SETT_ADS_SQUARE","Esquinas rectangulares");
DEFINE("_ADMIN_HWDVIDS_SETT_ADS_SR","Esquinas ligeramente redondeadas");
DEFINE("_ADMIN_HWDVIDS_SETT_ADS_VR","Esquinas muy redondeadas");
DEFINE("_ADMIN_HWDVIDS_SETT_AD1LAYOUT","Disposición de la publicidad");
DEFINE("_ADMIN_HWDVIDS_SETT_AD1LAYOUT_DESC","Elige el formato y el tamaño de la publicidad para tu página.");
DEFINE("_ADMIN_HWDVIDS_SETT_AD1FORM1","468 x 60 Banner");
DEFINE("_ADMIN_HWDVIDS_SETT_AD1FORM2","234 x 60 Half Banner");
DEFINE("_ADMIN_HWDVIDS_SETT_AD1FORM3","120 x 600 Skyscraper");
DEFINE("_ADMIN_HWDVIDS_SETT_AD1FORM4","160 x 600 Wide Skyscraper");
DEFINE("_ADMIN_HWDVIDS_SETT_AD1FORM5","120 x 240 Vertical Banner");
DEFINE("_ADMIN_HWDVIDS_SETT_AD1FORM6","336 x 280 Large Rectangle");
DEFINE("_ADMIN_HWDVIDS_SETT_AD1FORM7","300 x 250 Medium rectangle");
DEFINE("_ADMIN_HWDVIDS_SETT_AD1FORM8","250 x 250 Cuadrado");
DEFINE("_ADMIN_HWDVIDS_SETT_AD1FORM9","200 x 200 Cuadrado pequeño");
DEFINE("_ADMIN_HWDVIDS_SETT_AD1FORM10","180 x 150 Rectángulo pequeño");
DEFINE("_ADMIN_HWDVIDS_SETT_AD1FORM11","125 x 125 Botón");
DEFINE("_ADMIN_HWDVIDS_SETT_AD1FORM12","728 x 90 Leaderboard");
DEFINE("_ADMIN_HWDVIDS_SETT_AD1FORM13","728 x 15 Adlink 4 links");
DEFINE("_ADMIN_HWDVIDS_SETT_AD1FORM14","468 x 15 Adlink 4 links");
DEFINE("_ADMIN_HWDVIDS_SETT_AD1FORM15","120 x 90 Adlink 4 links");
DEFINE("_ADMIN_HWDVIDS_SETT_AD1FORM16","160 x 90 Adlink 4 links");
DEFINE("_ADMIN_HWDVIDS_SETT_AD1FORM17","180 x 90 Adlink 4 links");
DEFINE("_ADMIN_HWDVIDS_SETT_AD1FORM18","200 x 90 Adlink 4 links");
DEFINE("_ADMIN_HWDVIDS_SETT_AD1FORM19","728 x 15 Adlink 5 links");
DEFINE("_ADMIN_HWDVIDS_SETT_AD1FORM20","468 x 15 Adlink 5 links");
DEFINE("_ADMIN_HWDVIDS_SETT_AD1FORM21","120 x 90 Adlink 5 links");
DEFINE("_ADMIN_HWDVIDS_SETT_AD1FORM22","160 x 90 Adlink 5 links");
DEFINE("_ADMIN_HWDVIDS_SETT_AD1FORM23","180 x 90 Adlink 5 links");
DEFINE("_ADMIN_HWDVIDS_SETT_AD1FORM24","200 x 90 Adlink 5 links");
DEFINE("_ADMIN_HWDVIDS_SETT_AD1ADBORDER","Color de borde");
DEFINE("_ADMIN_HWDVIDS_SETT_AD1ADBORDER_DESC","Color de borde, en hexadecimal, sin #");
DEFINE("_ADMIN_HWDVIDS_SETT_AD1ADBG","Color de fondo");
DEFINE("_ADMIN_HWDVIDS_SETT_AD1ADBG_DESC","Color de fondo, en hexadecimal, sin #");
DEFINE("_ADMIN_HWDVIDS_SETT_AD1ADLINK","Color de enlace");
DEFINE("_ADMIN_HWDVIDS_SETT_AD1ADLINK_DESC","Color de enlace, en hexadecimal, sin #");
DEFINE("_ADMIN_HWDVIDS_SETT_AD1ADTEXT","Color de texto");
DEFINE("_ADMIN_HWDVIDS_SETT_AD1ADTEXT_DESC","Color de texto, en hexadecimal, sin #");
DEFINE("_ADMIN_HWDVIDS_SETT_AD1ADURL","Color de URL");
DEFINE("_ADMIN_HWDVIDS_SETT_AD1ADURL_DESC","Color de URL, en hexadecimal, sin #");
DEFINE("_ADMIN_HWDVIDS_SETT_AD1UIF","Estilo de esquinas");
DEFINE("_ADMIN_HWDVIDS_SETT_AD1UIF_DESC","Opcionalmente, elige uno de los estilos prediseñados de esquinas.");
DEFINE("_ADMIN_HWDVIDS_SETT_FLVAUTOSTART","Autocomenzar");
DEFINE("_ADMIN_HWDVIDS_SETT_FLVAUTOSTART_DESC","¿Comienza a reproducir el vídeo automáticamente cuando la página se carga?");
DEFINE("_ADMIN_HWDVIDS_SETT_FLVOVERSTRETCH","¿Estirar vídeo?");
DEFINE("_ADMIN_HWDVIDS_SETT_FLVOVERSTRETCH_DESC","Esto estirará el vídeo para ajustarse al tamaño del reproductor, ignorando las dimensiones originales del fichero de vídeo. [VER ABAJO INSTRUCCIONES DE USO]");
DEFINE("_ADMIN_HWDVIDS_SETT_FLVLOGO","Logotipo del reproductor");
DEFINE("_ADMIN_HWDVIDS_SETT_FLVLOGO_DESC","Indica una imagen que puede ser colocada como marca de agua en el reproductor de vídeo. Los ficheros PNG transparentes son los que darán mejores resultados. [VER ABAJO INSTRUCCIONES DE USO]");
DEFINE("_ADMIN_HWDVIDS_SETT_FLVVOLUME","Volumen inicial");
DEFINE("_ADMIN_HWDVIDS_SETT_FLVVOLUME_DESC","Volumen inicial del reproductor. El usuario puede cambiarlo con posterioridad [VER ABAJO INSTRUCCIONES DE USO]");
DEFINE("_ADMIN_HWDVIDS_SETT_FLVBG","Color de fondo");
DEFINE("_ADMIN_HWDVIDS_SETT_FLVBG_DESC","Color de fondo de los controles del reproductor, en formato hexadecimal. [VER ABAJO INSTRUCCIONES DE USO]");
DEFINE("_ADMIN_HWDVIDS_SETT_FLVFG","Color de primer plano");
DEFINE("_ADMIN_HWDVIDS_SETT_FLVFG_DESC","Color de primer plano de los controles del reproductor, en formato hexadecimal. [VER ABAJO INSTRUCCIONES DE USO]");
DEFINE("_ADMIN_HWDVIDS_SETT_FPORDER","Orden de los vídeos de la página principal");
DEFINE("_ADMIN_HWDVIDS_SETT_FPORDER_DESC","Selecciona el orden de las listas de vídeo del componente de la página principal");
DEFINE("_ADMIN_HWDVIDS_SETT_FPORDER_RECENT","Más recientes");
DEFINE("_ADMIN_HWDVIDS_SETT_FPORDER_POPULAR","Más populares");
DEFINE("_ADMIN_HWDVIDS_SETT_FPORDER_VIEWED","Más vistos");
DEFINE("_ADMIN_HWDVIDS_SETT_PERLSCRIPTSETUP","Cómo configurar el método de subida avanzado Perl");
DEFINE("_ADMIN_HWDVIDS_SETT_VERIFYTHUMBSEXIST","¿Verificar si las miniaturas de terceros existen?");
DEFINE("_ADMIN_HWDVIDS_SETT_VERIFYTHUMBSEXIST_DESC","hwdVideoShare intenta verificar la existencia de miniaturas de imágenes de terceros (de YouTube, Google Video etc) con la función de php <b>get_headers</b>. Si la imagen no existe se mostrará la imagen por defecto. Adicionalmente, si la función <b>get_headers</b> no está disponible entonces la imagen se mostrará siempre, independientemente de si la imagen real existe o no. Establece este valor a No si quieres que se sobreescriba esta opción y siempre se muestre la imagen de terceros sin verificar su existencia con la función <b>get_headers</b>.");
DEFINE("_ADMIN_HWDVIDS_SETT_RATESYS","Método de puntuación de vídeos");
DEFINE("_ADMIN_HWDVIDS_SETT_FAVSYS","Método favorito para añadir");
DEFINE("_ADMIN_HWDVIDS_SETT_FAVSYS_DESC","Elige el método (POST o AJAX) que los usuarios utilizarán para añadir vídeos a sus favoritos. El método AJAX no interrumpirá la reproducción de vídeo.");
DEFINE("_ADMIN_HWDVIDS_SETT_REPORTSYS","Método de denuncia de vídeo");
DEFINE("_ADMIN_HWDVIDS_SETT_REPORTSYS_DESC","Elige el método (POST o AJAX) que los usuarios utilizarán para denunciar vídeos inapropiados. El método AJAX no interrumpirá la reproducción de vídeo.");
DEFINE("_ADMIN_HWDVIDS_SETT_A2GSYS","Método de añadir a grupo.");
DEFINE("_ADMIN_HWDVIDS_SETT_A2GSYS_DESC","Elige el método (POST o AJAX) que los usuarios utilizarán para añadir grupos. El método AJAX no interrumpirá la reproducción de vídeo.");
DEFINE("_ADMIN_HWDVIDS_SETT_BKP_1","¡hwdVideoShare acaba de realizar pruebas en tu servidor y cree que serás capaz de utilizar esta función sin problemas!");
DEFINE("_ADMIN_HWDVIDS_SETT_BKP_0","hwdVideoShare acaba de realizar pruebas en tu servidor y por desgracia esta función no funcionará");
DEFINE("_ADMIN_HWDVIDS_SETT_VPINTMET","Métodos de interacción de la página de vídeo");
DEFINE("_ADMIN_HWDVIDS_SETT_VPINFOOT","Opciones de información de página de vídeo");
DEFINE("_ADMIN_HWDVIDS_SETT_DISABLEUSRTABS","Desactivar la barra de navegación del usuario");
DEFINE("_ADMIN_HWDVIDS_SETT_DISABLEYVLINK","Desactivar el enlace <b>Tus vídeos</b>");
DEFINE("_ADMIN_HWDVIDS_SETT_DISABLEYVLINK_DESC","Desactiva este enlace en la barra de navegación del usuario de tal forma que no aparecerá");
DEFINE("_ADMIN_HWDVIDS_SETT_DISABLEYFLINK","Desactivar enlace <b>Tus favoritos</b>");
DEFINE("_ADMIN_HWDVIDS_SETT_DISABLEYFLINK_DESC","Desactiva este enlace en la barra de navegación del usuario de tal forma que no aparecerá");
DEFINE("_ADMIN_HWDVIDS_SETT_DISABLEYGLINK","Desactivar enlace <b>Tus grupos</b>");
DEFINE("_ADMIN_HWDVIDS_SETT_DISABLEYGLINK_DESC","Desactiva este enlace en la barra de navegación del usuario de tal forma que no aparecerá");
DEFINE("_ADMIN_HWDVIDS_SETT_DISABLEYMLINK","Desactivar enlace <b>Tu pertenencia a grupos</b>");
DEFINE("_ADMIN_HWDVIDS_SETT_DISABLEYMLINK_DESC","Desactiva este enlace en la barra de navegación del usuario de tal forma que no aparecerá");
DEFINE("_ADMIN_HWDVIDS_SETT_DISABLECGLINK","Desactivar enlace <b>Crear nuevo grupo</b>");
DEFINE("_ADMIN_HWDVIDS_SETT_DISABLECGLINK_DESC","Desactiva este enlace en la barra de navegación del usuario de tal forma que no aparecerá");
DEFINE("_ADMIN_HWDVIDS_SETT_SHOWRAT_DESC","Permite a los usuarios utilizar esta función cuando estén viendo un vídeo");
DEFINE("_ADMIN_HWDVIDS_SETT_SHOWATF","Activar la función <b>Añadir a favoritos</b>");
DEFINE("_ADMIN_HWDVIDS_SETT_SHOWATF_DESC","Permite a los usuarios utilizar esta función cuando estén viendo un vídeo");
DEFINE("_ADMIN_HWDVIDS_SETT_SHOWRPB","Activar la función <b>Denunciar vídeo</b>");
DEFINE("_ADMIN_HWDVIDS_SETT_SHOWRPB_DESC","Permite a los usuarios utilizar esta función cuando estén viendo un vídeo");
DEFINE("_ADMIN_HWDVIDS_SETT_SHOWCOM","Activar la función <b>Comentar</b>");
DEFINE("_ADMIN_HWDVIDS_SETT_SHOWCOM_DESC","Permite a los usuarios utilizar esta función cuando estén viendo un vídeo");
DEFINE("_ADMIN_HWDVIDS_SETT_SHOWVUR","Mostrar el enlace <b>URL del vídeo</b>");
DEFINE("_ADMIN_HWDVIDS_SETT_SHOWVUR_DESC","Permite a los usuarios utilizar esta función cuando estén viendo un vídeo");
DEFINE("_ADMIN_HWDVIDS_SETT_SHOWVEB","Mostrar el código <b>Incrustar vídeo</b>");
DEFINE("_ADMIN_HWDVIDS_SETT_SHOWVEB_DESC","Permite a los usuarios utilizar esta función cuando estén viendo un vídeo");
DEFINE("_ADMIN_HWDVIDS_SETT_SHOWDSC","Mostrar la <b>description</b> del vídeo");
DEFINE("_ADMIN_HWDVIDS_SETT_SHOWDSC_DESC","Permite a los usuarios ver este texto cuando están viendo un vídeo");
DEFINE("_ADMIN_HWDVIDS_SETT_SHOWTAG","Mostrar las <b>etiquetas</b> de vídeo");
DEFINE("_ADMIN_HWDVIDS_SETT_SHOWTAG_DESC","Permite a los usuarios ver este texto cuando están viendo un vídeo");
DEFINE("_ADMIN_HWDVIDS_SETT_SHOWSBK","Mostrar <b>Bookmarks social</b>");
DEFINE("_ADMIN_HWDVIDS_SETT_SHOWSBK_DESC","Permite a los usuarios ver este texto cuando están viendo un vídeo");
DEFINE("_ADMIN_HWDVIDS_SETT_SHOWA2G","Mostrar la función <b>añadir a grupo</b>");
DEFINE("_ADMIN_HWDVIDS_SETT_SHOWA2G_DESC","Permite a los usuarios añadir vídeos a grupos");
DEFINE("_ADMIN_HWDVIDS_SETT_PLAYERACCESS","Acceso al reproductor de vídeo");
DEFINE("_ADMIN_HWDVIDS_SETT_PLAYERACCESS_DESC","Establece los grupos de Joomla que pueden acceder al reproductor de vídeo y ver vídeos");
DEFINE("_ADMIN_HWDVIDS_SETT_LANGUAGE_DESC","Elige la extensión de idioma de hwdVideoShare. Para añadir más idiomas, instala las extensiones de idioma a través del gestor de extensiones.");
DEFINE("_ADMIN_HWDVIDS_SETT_VPLAYER","Elige el reproductor de vídeo");
DEFINE("_ADMIN_HWDVIDS_SETT_VPLAYER_DESC","Elige la extensión del reproductor de vídeo de hwdVideoShare. Para añadir otro reproductor, instala las extensiones del reproductor a través del gestor de extensiones.");
DEFINE("_ADMIN_HWDVIDS_SETT_MAXUPLDWARN1","<h3>Advertencia :: El tamaño máximo de subida está generando una advertencia</h3><p>El tamaño máximo de fichero es demasiado grande, hwdVideoShare reducirá automáticamente este ajuste al máximo permitido por tu servidor.</p><p style=\"font-size:80%\">El tamaño máximo de subida está limitado al ajuste <i>upload_max_filesize</i> de tu fichero php.ini.</p>");
DEFINE("_ADMIN_HWDVIDS_SETT_MAXUPLDWARN2","<h3>Advertencia :: El tamaño máximo de subida está generando una advertencia</h3><p>El tamaño máximo de subida es demasiado grande, hwdVideoShare reducirá automáticamente este ajuste al máximo permitido por tu servidor.</p><p style=\"font-size:80%\">Tu método de subida está limitado por el ajuste <i>post_max_size</i> de tu fichero php.ini.</p>");
DEFINE("_ADMIN_HWDVIDS_SETT_UPLDWARN1","<h3>Advertencia :: Tu método de subida está generando una advertencia</h3><p>hwdVideoShare no puede verificar que el método de subida Perl está configurado correctamente.</p>");
DEFINE("_ADMIN_HWDVIDS_SETT_UPLDWARN2","<h3>Error :: Tu método de subida está generando un error</h3><p>hwdVideoShare no cree que el método de subida avanzado Perl esté configurado correctamente.</p>");
DEFINE("_ADMIN_HWDVIDS_SETT_ACCESSSET","Ajustes de acceso");
DEFINE("_ADMIN_HWDVIDS_SETT_ACCESSMETHOD","Método de verificación de acceso");
DEFINE("_ADMIN_HWDVIDS_SETT_ACCESSMETHOD_DESC","¿Quieres indicar acceso por <b>Grupos de acceso</b> o por <b>Niveles de acceso</b>?");
DEFINE("_ADMIN_HWDVIDS_SETT_ACCESSGRP","Grupos de acceso");
DEFINE("_ADMIN_HWDVIDS_SETT_ACCESSLEV","Niveles de acceso");
DEFINE("_ADMIN_HWDVIDS_SETT_XMLPL","XML Shareable Playlists (XSPL)");
DEFINE("_ADMIN_HWDVIDS_SETT_XMLPL_DESC","XML Shareable Playlist Format (XSPF), que se pronuncia spiff, es un formato de listas de reproducción basado en XML para medios digitales, patroinado por la fundación Xiph.Org. Lucas Gonze de Yahoo.com/Webjay.org creó el formato en 2004. XSPF es un formato de datos para compartir un tipo de listas de reproducción que pueden ser reproducidas en un ordenador personal o en un dispositivo portátil. De la misma forma que cualquier usuario en un ordenador puede abrir cualquier página web, XSPF pretende proporcionar portabilidad para las listas de reproducción.");
DEFINE("_ADMIN_HWDVIDS_SETT_XMLPLCACHE_TODAY","Caché de lista de reproducción [Hoy]");
DEFINE("_ADMIN_HWDVIDS_SETT_XMLPLCACHE_TODAY_DESC","El tiempo para cachear las listas de reproducción XML para los resultados de hoy. Las listas de reproducción se regenerarán después de esta cantidad de tiempo.");
DEFINE("_ADMIN_HWDVIDS_SETT_XMLPLCACHE_TW","Caché de lista de reproducción [Esta semana]");
DEFINE("_ADMIN_HWDVIDS_SETT_XMLPLCACHE_TW_DESC","El tiempo para cachear las listas de reproducción XML para los resultados de esta semana. Las listas de reproducción se regenerarán después de esta cantidad de tiempo.");
DEFINE("_ADMIN_HWDVIDS_SETT_XMLPLCACHE_TM","Caché de lista de reproducción [Este mes]");
DEFINE("_ADMIN_HWDVIDS_SETT_XMLPLCACHE_TM_DESC","El tiempo para cachear las listas de reproducción XML para los resultados de este mes. Las listas de reproducción se regenerarán después de esta cantidad de tiempo.");
DEFINE("_ADMIN_HWDVIDS_SETT_XMLPLCACHE_AT","Caché de lista de reproducción [Siempre]");
DEFINE("_ADMIN_HWDVIDS_SETT_XMLPLCACHE_AT_DESC","El tiempo para cachear las listas de reproducción XML para todos los resultados. Las listas de reproducción se regenerarán después de esta cantidad de tiempo.");
DEFINE("_ADMIN_HWDVIDS_SETT_CUSTOMXML","Lista de reproducción personalizada");
DEFINE("_ADMIN_HWDVIDS_SETT_CUSTOMXML_DESC","Crea tus propias listas de reproducción mediante identificadores de vídeo separados por coma, por ejemplo: 34, 543, 48, 97, 234");
DEFINE("_ADMIN_HWDVIDS_SETT_CACHENO","No cachear");
DEFINE("_ADMIN_HWDVIDS_SETT_CACHE60","60 Segundos (Cada minuto)");
DEFINE("_ADMIN_HWDVIDS_SETT_CACHE300","300 Segundos (Cada 5 minutos)");
DEFINE("_ADMIN_HWDVIDS_SETT_CACHE600","600 Segundos (Cada 10 minutos)");
DEFINE("_ADMIN_HWDVIDS_SETT_CACHE1800","1800 Segundos (Cada 30 minutos)");
DEFINE("_ADMIN_HWDVIDS_SETT_CACHE3600","3600 Segundos (Cada hora)");
DEFINE("_ADMIN_HWDVIDS_SETT_CACHE18000","18000 Segundos (Cada 5 horas)");
DEFINE("_ADMIN_HWDVIDS_SETT_CACHE36000","36000 Segundos (Cada 10 horas)");
DEFINE("_ADMIN_HWDVIDS_SETT_CACHE86400","86000 Segundos (Diariamente)");
DEFINE("_ADMIN_HWDVIDS_SETT_CACHE604800","604800 Segundos (Semanalmente)");
DEFINE("_ADMIN_HWDVIDS_SETT_TPMETHOD","Vídeos de terceros");
DEFINE("_ADMIN_HWDVIDS_SETT_TPFUNC","Método de transferencia principal");
DEFINE("_ADMIN_HWDVIDS_SETT_TPFUNC_DESC","Elige entre la función <a href=\"http://php.net/curl\" target=\"_blank\">CURL</a> y la función <a href=\"http://php.net/file_get_contents\" target=\"_blank\">file_get_contents</a> cuando se transmitan datos desde páginas webs de terceros. (CURL es más seguro.)");
DEFINE("_ADMIN_HWDVIDS_SETT_PTHL","Reproducir en el reproductor local");
DEFINE("_ADMIN_HWDVIDS_SETT_PTHL_DESC","Siempre que sea posible, reproduce los vídeos de terceros en el reproductor local (en lugar de utilizar el reproductor de terceros).");
DEFINE("_ADMIN_HWDVIDS_SETT_AAVIDS","¿Auto-aprobar vídeos subidos?");
DEFINE("_ADMIN_HWDVIDS_SETT_SAUPLD","Automáticamente convertir vídeos");
DEFINE("_ADMIN_HWDVIDS_SETT_SAUPLD_DESC","¿Quieres enviar los ficheros de vídeos subidos directamente al conversor para ser procesados inmediatamente después de que la subida haya sido completada?<br />Esto enviará el fichero de vídeo para ser convertido en un proceso de segundo plano (<b>> /dev/null &</b>). Si eliges Sí y tus vídeos no son automáticamente convertidos queire decir que <b>tu servidor no soporta esta función</b>.");
DEFINE("_ADMIN_HWDVIDS_SETT_UPLDMETH_BASPHP","El <a href=\"http://documentation.hwdmediashare.co.uk/wiki/Basic_PHP_Upload_Method\" target=\"_blank\"><b>Método básico de subida (PHP)</b></a> utiliza sólo php para procesar las subidas de ficheros de vídeo. No debería requerir ninguna configuración manual para que funcione correctamente, pero tendrá límites de subida más pequeños por norma general.");
DEFINE("_ADMIN_HWDVIDS_SETT_RESTRICTPHP","Limitaciones de subida de PHP");
DEFINE("_ADMIN_HWDVIDS_SETT_MAXUPLD_PHP","Tu servidor tiene las siguientes limitaciones en el tamaño máximo de vídeo.");
DEFINE("_ADMIN_HWDVIDS_SETT_NO_PARAMS","Sin parámetros.");
DEFINE("_ADMIN_HWDVIDS_SETT_FRONTPAGE","Vídeos de la página principal");
DEFINE("_ADMIN_HWDVIDS_SETT_SHOWWN","Mostrar vídeos viéndose ahora mismo");
DEFINE("_ADMIN_HWDVIDS_SETT_SHOWWN_DESC","La lista de vídeos viéndose ahora mismo estará disponible en la galería de vídeos de la página principal");
DEFINE("_ADMIN_HWDVIDS_SETT_SHOWMV","Mostrar vídeos más vistos");
DEFINE("_ADMIN_HWDVIDS_SETT_SHOWMV_DESC","La lista de vídeos más vistos estará disponible en la galería de vídeos de la página principal");
DEFINE("_ADMIN_HWDVIDS_SETT_SHOWMF","Mostrar los vídeos favoritos");
DEFINE("_ADMIN_HWDVIDS_SETT_SHOWMF_DESC","La lista de los vídeos favoritos estará disponible en la galería de vídeos de la página");
DEFINE("_ADMIN_HWDVIDS_SETT_SHOWMP","Mostrar los vídeos más populares ");
DEFINE("_ADMIN_HWDVIDS_SETT_SHOWMP_DESC","La lista de los vídeos más populares estará disponible en la galería de vídeos de la página");
DEFINE("_ADMIN_HWDVIDS_SETT_SHOWULR","Mostrar <b>Más de este usuario</b>");
DEFINE("_ADMIN_HWDVIDS_SETT_SHOWULR_DESC","Permite a los usuarios ver quién subió este vídeo y más vídeos del usuario");
DEFINE("_ADMIN_HWDVIDS_SETT_NOTIFYR","¿Notificar después de una nueva denuncia?");
DEFINE("_ADMIN_HWDVIDS_SETT_NOTIFYR_DESC","Envía una notificación de correo cuando un usuario denuncia un vídeo como inapropiado");
DEFINE("_ADMIN_HWDVIDS_SETT_CONVERTSWF","Reproducción de los ficheros SWF");
DEFINE("_ADMIN_HWDVIDS_SETT_SWFSA","¿Reproducir vídeos swf de forma independiente?");
DEFINE("_ADMIN_HWDVIDS_SETT_SWFSA_DESC","Elige si quieres que los ficheros swf se incrusten como un objeto independiente o se reproduzcan en el reproductor de vídeo.");
DEFINE("_ADMIN_HWDVIDS_SETT_PATHSL","Ruta a las bibliotecas compartidas");
DEFINE("_ADMIN_HWDVIDS_SETT_PATHSL_DESC","Temporalmente susutituye una biblioteca diferente para las ejecuciones de conversión de hwdVideoShare.");
DEFINE("_ADMIN_HWDVIDS_SETT_JACLINT","Integración con JACL");
DEFINE("_ADMIN_HWDVIDS_SETT_INTJACL","¿Integrar con JACL Plus?");
DEFINE("_ADMIN_HWDVIDS_SETT_INTJACL_DESC","La integración con JACL Plus permitirá gestionar el acceso a hwdVideoShare a través de niveles de acceso.");
DEFINE("_ADMIN_HWDVIDS_SETT_FTODAY","De hoy");
DEFINE("_ADMIN_HWDVIDS_SETT_FTW","De esta semana");
DEFINE("_ADMIN_HWDVIDS_SETT_FTM","De este mes");
DEFINE("_ADMIN_HWDVIDS_SETT_FAT","Desde siempre");
DEFINE("_ADMIN_HWDVIDS_SETT_TPWIDTH","Ancho del reproductor de vídeo de terceros");
DEFINE("_ADMIN_HWDVIDS_SETT_TPWIDTH_DESC","Si hwdVideoShare incrusta un reproductor de vídeo de una página web externa es posible establecer el ancho aquí. El alto será calculado automáticamente para este formato de página web. Por ejemplo, si reproduces un vídeo que está en formato panorámico, se mostrará en formato panorámico.");
DEFINE("_ADMIN_HWDVIDS_SETT_RATESYS_DESC","Selecciona el método (POST o AJAX) que los usuarios utilizarán para puntuar vídeos. El método AJAX no interrumpirá la reproducción.");
DEFINE("_ADMIN_HWDVIDS_SETT_INTEGRATIONSCB","Integración con Community");
DEFINE("_ADMIN_HWDVIDS_SETT_INTCB","¿Integrar con Community?");
DEFINE("_ADMIN_HWDVIDS_SETT_INTCB_DESC","Esta integración permite que los usuarios envían perfiles de community");
DEFINE("_ADMIN_HWDVIDS_SETT_SHOWCBAVA","¿Mostrar un Avatar de Community?");
DEFINE("_ADMIN_HWDVIDS_SETT_SHOWCBAVA_DESC","¿Mostrar imágenes de avatar en hwdVideoShare?");
DEFINE("_ADMIN_HWDVIDS_SETT_CBITEMID","Itemid de Community");
DEFINE("_ADMIN_HWDVIDS_SETT_CBITEMID_DESC","Para asegurarse de que hwdVideoShare apunta al la página correcta del perfil añade el Itemid de Community. Acude a nuestra documentación para obtener más ayuda.");
DEFINE("_ADMIN_HWDVIDS_SETT_THUMBW_DESC","Establece el ancho de las miniaturas de vídeo. Por defecto es 120.");
DEFINE("_ADMIN_HWDVIDS_SETT_VAR","Relación aspecto del vídeo");
DEFINE("_ADMIN_HWDVIDS_SETT_CVAR","¿Calcular la relación de aspecto del vídeo?");
DEFINE("_ADMIN_HWDVIDS_SETT_CVAR_DESC","Intenta calcular automáticamente la relación de aspecto del vídeo");
DEFINE("_ADMIN_HWDVIDS_SETT_VFR","Relación de aspecto por defecto");
DEFINE("_ADMIN_HWDVIDS_SETT_VFR_DESC","Relación de aspecto por defecto si no es posible calcularlo automáticamente");
DEFINE("_ADMIN_HWDVIDS_SETT_VTC","Configuración de la miniatura de vídeo");
DEFINE("_ADMIN_HWDVIDS_SETT_TAR","Relación de aspecto de la miniatura de vídeo");
DEFINE("_ADMIN_HWDVIDS_SETT_TAR_DESC","Relación de aspecto para las miniaturas");
DEFINE("_ADMIN_HWDVIDS_SETT_UDT","Utilizar miniaturas dinámicas");
DEFINE("_ADMIN_HWDVIDS_SETT_UDT_DESC","Utiliza miniaturas dinámicas que van mostrando capturas del vídeo");
DEFINE("_ADMIN_HWDVIDS_SETT_OFORMATS","Otros formatos soportados");
DEFINE("_ADMIN_HWDVIDS_SETT_OFORMATS_DESC","Añade soporte a formatos extra en hwdVideoShare");
DEFINE("_ADMIN_HWDVIDS_SETT_NBWNO","Número de vídeos en <b>viéndose ahora mismo</b>");
DEFINE("_ADMIN_HWDVIDS_SETT_NBWNO_DESC","Establece el número de vídeos a mostrar en Viéndose Ahora Mismo");
DEFINE("_ADMIN_HWDVIDS_SETT_SOFTINS","¿Programas de conversión de vídeo instalados?");
DEFINE("_ADMIN_HWDVIDS_SETT_SOFTINS_DESC","¿Tiene tu servidor los requisitos necesarios instalados? Este programa es necesario para procesar los ficheros de vídeo subidos.");
DEFINE("_ADMIN_HWDVIDS_SETT_ORDERING","Ordenación de listas por defecto");
DEFINE("_ADMIN_HWDVIDS_SETT_CORDERING","Ordenación de categoría");
DEFINE("_ADMIN_HWDVIDS_SETT_CORDERING_DESC","Ordena la lista de categorías real");
DEFINE("_ADMIN_HWDVIDS_SETT_CVORDERING","Ordenación de vídeos de categoría");
DEFINE("_ADMIN_HWDVIDS_SETT_CVORDERING_DESC","Ordena los vídeos cuando se ven vídeos en categorías");
DEFINE("_ADMIN_HWDVIDS_SETT_CUSTORDERING_DESC","Permite a los usuarios ordenar las listas como quieran");
DEFINE("_ADMIN_HWDVIDS_SETT_UPLOADACCESS","Acceso a la función de subida local");
DEFINE("_ADMIN_HWDVIDS_SETT_UPLOADACCESS_DESC","Establece los grupos que podrán subir vídeos locales al componentehwdVideoShare");
DEFINE("_ADMIN_HWDVIDS_SETT_TPUPLOADACCESS","Acceso a la función de subida de terceros");
DEFINE("_ADMIN_HWDVIDS_SETT_TPUPLOADACCESS_DESC","Establece los grupos que pueden subir vídeos de terceros al componente hwdVideoShare");
DEFINE("_ADMIN_HWDVIDS_SETT_DNLDACCESS","Acceso a las descargas de vídeos");
DEFINE("_ADMIN_HWDVIDS_SETT_DNLDACCESS_DESC","Establece los grupos que pueden descargar vídeos del componente hwdVideoShare");
DEFINE("_ADMIN_HWDVIDS_SETT_BVIIC","Ocultar vídeos restringidos en las listas");
DEFINE("_ADMIN_HWDVIDS_SETT_BVIIC_DESC","Oculta los vídeos para los que el usuario no tiene acceso en las listas.");
DEFINE("_ADMIN_HWDVIDS_SETT_CUSTORDERING","¿Los usuarios eligen la ordenación?");
DEFINE("_ADMIN_HWDVIDS_SETT_LOGCONVERT_DESC","Crear un fichero de registro de las conversiones de vídeo (Almacenado en JoomlaRoot/media/hwdVideoShare_VideoConversionLog.dat)");
DEFINE("_ADMIN_HWDVIDS_VBITRATE","Bitrate de vídeo");
DEFINE("_ADMIN_HWDVIDS_VBITRATE_DESC","Establece el bitrate de vídeo en kbit/s (Por defecto 200 kb/s)");
DEFINE("_ADMIN_HWDVIDS_ABITRATE","Bitrate de audio");
DEFINE("_ADMIN_HWDVIDS_ABITRATE_DESC","Establece el bitrate de audio en kbit/s (Por defecto 64 kbit/s)");
DEFINE("_ADMIN_HWDVIDS_ASR","Frecuencia de muestreo de audio");
DEFINE("_ADMIN_HWDVIDS_ASR_DESC","Establece la frecuencia de muestreo del audio en Hz (Por defecto 22050 Hz)");
DEFINE("_ADMIN_HWDVIDS_FSIZE","Tamaño del vídeo");
DEFINE("_ADMIN_HWDVIDS_FSIZE_DESC","Establece el tamaño del vídeo.");
DEFINE("_ADMIN_HWDVIDS_VBITRATE_VP","16 kbit/s - Calidad de videoteléfono");
DEFINE("_ADMIN_HWDVIDS_VBITRATE_VC2","200 kbit/s - Calidad de sistema de videoconferencia");
DEFINE("_ADMIN_HWDVIDS_VBITRATE_VC3","300 kbit/s - Calidad de sistema de videoconferencia");
DEFINE("_ADMIN_HWDVIDS_VBITRATE_VC4","400 kbit/s - Calidad de sistema de videoconferencia");
DEFINE("_ADMIN_HWDVIDS_VBITRATE_VC5","500 kbit/s - Calidad de sistema de videoconferencia");
DEFINE("_ADMIN_HWDVIDS_VBITRATE_VC6","600 kbit/s - Calidad de sistema de videoconferencia");
DEFINE("_ADMIN_HWDVIDS_VBITRATE_VC7","700 kbit/s - Calidad de sistema de videoconferencia");
DEFINE("_ADMIN_HWDVIDS_VBITRATE_VC8","800 kbit/s - Calidad de sistema de videoconferencia");
DEFINE("_ADMIN_HWDVIDS_VBITRATE_VC9","900 kbit/s - Calidad de sistema de videoconferencia");
DEFINE("_ADMIN_HWDVIDS_VBITRATE_VC10","1000 kbit/s - Calidad de sistema de videoconferencia");
DEFINE("_ADMIN_HWDVIDS_VBITRATE_VCD15","1500 kbit/s - Calidad VCD");
DEFINE("_ADMIN_HWDVIDS_VBITRATE_VCD20","2000 kbit/s - Calidad VCD");
DEFINE("_ADMIN_HWDVIDS_VBITRATE_VCD25","2500 kbit/s - Calidad VCD");
DEFINE("_ADMIN_HWDVIDS_VBITRATE_VCD30","3000 kbit/s - Calidad VCD");
DEFINE("_ADMIN_HWDVIDS_VBITRATE_VCD35","3500 kbit/s - Calidad VCD");
DEFINE("_ADMIN_HWDVIDS_VBITRATE_VCD40","4000 kbit/s - Calidad VCD");
DEFINE("_ADMIN_HWDVIDS_VBITRATE_VCD45","4500 kbit/s - Calidad VCD");
DEFINE("_ADMIN_HWDVIDS_VBITRATE_VCD","1250 kbit/s - Calidad VCD");
DEFINE("_ADMIN_HWDVIDS_VBITRATE_DVD","5000 kbit/s - Calidad DVD");
DEFINE("_ADMIN_HWDVIDS_VBITRATE_HDTV","15000 kbit/s - Calidad HDTV");
DEFINE("_ADMIN_HWDVIDS_ABITRATE_AM","32 kbit/s - Calidad AM");
DEFINE("_ADMIN_HWDVIDS_ABITRATE_DF","64 kbit/s - Calidad por defecto");
DEFINE("_ADMIN_HWDVIDS_ABITRATE_FM","96 kbit/s - Calidad FM");
DEFINE("_ADMIN_HWDVIDS_ABITRATE_ST","128 kbit/s - Calidad de bitrate standard");
DEFINE("_ADMIN_HWDVIDS_ABITRATE_DBA","192 kbit/s - Calidad DAB (Digital Audio Broadcasting)");
DEFINE("_ADMIN_HWDVIDS_ABITRATE_CD","224 kbit/s - Calidad CD");
DEFINE("_ADMIN_HWDVIDS_ASR_TELE","8,000 Hz - Teléfono y walkie-talkie cifrado");
DEFINE("_ADMIN_HWDVIDS_ASR_QURT","11,025 Hz - Un cuarto de la frecuencia de muestreo de los CDs de audio; utilizado para una calidad más baja de PCM");
DEFINE("_ADMIN_HWDVIDS_ASR_HALF","22,050 Hz - La mitad de la frecuencia de muestreo de los CDs de audio; utilizado par auna calidad menor al PCM");
DEFINE("_ADMIN_HWDVIDS_ASR_MINIDV","32,000 Hz - Grabadora de vídeo digital MiniDV");
DEFINE("_ADMIN_HWDVIDS_ASR_NTSC","44,056 Hz - Adaptador PCM utilizando cintas de vídeo NTSC");
DEFINE("_ADMIN_HWDVIDS_ASR_CD","44,100 Hz - CD de audio");
DEFINE("_ADMIN_HWDVIDS_ASR_PCM","47,250 Hz - Primer PCM comercial");
DEFINE("_ADMIN_HWDVIDS_ASR_DTV","48,000 Hz - Sonido digital utilizado par miniDV y televisión digital");
DEFINE("_ADMIN_HWDVIDS_ASR_AREC","50,000 Hz - Primera grabadora digital comercial de 3M y Soundstream");
DEFINE("_ADMIN_HWDVIDS_FSIZE_DF","POR DEFECTO 160x128 [4:3]");
DEFINE("_ADMIN_HWDVIDS_FSIZE_QVGA","QVGA 320x240 [4:3]");
DEFINE("_ADMIN_HWDVIDS_FSIZE_CGA","CGA 320x200 [8:5]");
DEFINE("_ADMIN_HWDVIDS_FSIZE_VGA","VGA 640x480 [4:3]");
DEFINE("_ADMIN_HWDVIDS_FSIZE_NTSC","NTSC 720x480 [3:2]");
DEFINE("_ADMIN_HWDVIDS_FSIZE_PAL","PAL 768x576 [4:3]");
DEFINE("_ADMIN_HWDVIDS_FSIZE_SVGA","SVGA 800x600 [4:3]");
DEFINE("_ADMIN_HWDVIDS_FSIZE_WVGA1","WVGA 800x480 [5:3]");
DEFINE("_ADMIN_HWDVIDS_FSIZE_WVGA2","WVGA 854x480 [16:9]");
DEFINE("_ADMIN_HWDVIDS_FSIZE_WSVGA","WSVGA 1024x600");
DEFINE("_ADMIN_HWDVIDS_FSIZE_SXGA","SXGA 1280x1024 [5:4]");
DEFINE("_ADMIN_HWDVIDS_FSIZE_HD720","HD720 1280x720 [16:9]");
DEFINE("_ADMIN_HWDVIDS_FSIZE_WXGA1","WXGA 1280x768 [5:3]");
DEFINE("_ADMIN_HWDVIDS_FSIZE_WXGA2","WXGA 1280x800 [8:5]");
DEFINE("_ADMIN_HWDVIDS_SETT_CBAVAWIDTH_DESC","Ancho (en pixels) de una imagen de avatar. Utilizar una imagen grande pixelará la imagen.");
DEFINE("_ADMIN_HWDVIDS_SETT_SOFTINS_YES","Si se selecciona Sí, podrás utilizar hwdVideoShare con todo su potencial y admitir subidas en la mayoría de los formatos más populares.");
DEFINE("_ADMIN_HWDVIDS_SETT_SOFTINS_NO","Si se selecciona No, no podrás convertir vídeos. hwdVideoShare sólo aceptará subidas en formato flv.");
DEFINE("_ADMIN_HWDVIDS_SETT_YES","Sí");
DEFINE("_ADMIN_HWDVIDS_SETT_NO","No");
DEFINE("_ADMIN_HWDVIDS_SETT_INCLUDECHILD","¿Incluir los grupos hijo?");
DEFINE("_ADMIN_HWDVIDS_SELECT_TEMPLATE","Seleccionar plantilla");
DEFINE("_ADMIN_HWDVIDS_SELECT_LANGUAGE","Seleccionar idioma");
DEFINE("_ADMIN_HWDVIDS_SELECT_PLAYER","Seleccionar reproductor");
DEFINE("_ADMIN_HWDVIDS_DEFAULT_TEMPLATE","Plantilla por defecto");
DEFINE("_ADMIN_HWDVIDS_LANGUAGE_ENGLISH","Idioma inglés");
DEFINE("_ADMIN_HWDVIDS_LANGUAGE_JOOMFISH","Idioma principal de Joomla");
DEFINE("_ADMIN_HWDVIDS_SETT_SHOWRAT","Activar <b>Funciones de puntuación</b>");
DEFINE("_ADMIN_HWDVIDS_HIDEUPLDNA","Utilizar ajustes de acceso");



DEFINE("_ADMIN_HWDVIDS_SETT_DISABLEPLTAB","Desactivar la pestaña de lista de reproducción");
DEFINE("_ADMIN_HWDVIDS_SETT_DISABLEPLTAB_DESC","Desactivar la pestaña de lista de reproducción de forma que el enlace no aparecerá en la parte superior de la página");

DEFINE("_ADMIN_HWDVIDS_SETT_DISABLECHTAB","Desactivar la pestaña de canal");
DEFINE("_ADMIN_HWDVIDS_SETT_DISABLECHTAB_DESC","Desactiva la pestaña de canal de forma que el enlace no aparecerá en la parte superior de la página");

DEFINE("_ADMIN_HWDVIDS_SETT_UPLDMETH_REMWARP","El <a href=\"http://documentation.hwdmediashare.co.uk/wiki/Remote_(WARP_HD)_Upload_Method\" target=\"_blank\"><b>método remoto (WARP HD)</b></a> permite subir, convertir y enviar vídeos desde un servicio de WARP HD remoto.");
